<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AsanNobat.Domain</RootNamespace>
    <AssemblyName>AsanNobat.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BusinessAgg\Exceptions\" />
  </ItemGroup>

</Project>
