<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AsanNobat.Application</RootNamespace>
    <AssemblyName>AsanNobat.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Mapster.DependencyInjection" />
    <PackageReference Include="Mediator.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BusinessAgg\Commands\RemoveBusiness\" />
    <Folder Include="BusinessAgg\Commands\CreateService\" />
    <Folder Include="BusinessAgg\Commands\CreateProvider\" />
    <Folder Include="BusinessAgg\Commands\CreateServiceToProvider\" />
    <Folder Include="BusinessAgg\Commands\CreateCounter\" />
    <Folder Include="BusinessAgg\Commands\CreateServiceToCounter\" />
    <Folder Include="BusinessAgg\Commands\RemoveServiceToCounter\" />
    <Folder Include="BusinessAgg\Commands\RemoveCounter\" />
    <Folder Include="BusinessAgg\Commands\UpdateCounter\" />
    <Folder Include="BusinessAgg\Commands\RemoveServiceToProvider\" />
    <Folder Include="BusinessAgg\Commands\RemoveProvider\" />
    <Folder Include="BusinessAgg\Commands\UpdateProvider\" />
    <Folder Include="BusinessAgg\Commands\RemoveService\" />
    <Folder Include="BusinessAgg\Commands\UpdateService\" />
    <Folder Include="BusinessAgg\EventHandlers\" />
    <Folder Include="BusinessAgg\Queries\" />
  </ItemGroup>

</Project>
