<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AsanNobat.TestAppHost</RootNamespace>
    <AssemblyName>AsanNobat.TestAppHost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.SQLite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Shared.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
